export default {
  state: { 
    tours: [
      {
        hot: true, 
        img: require("./../../assets/tours/1.jpeg"), 
        name: "A Taste of China", 
        country: "China", 
        dates: [
          {d: 2, m: 3, y: 2018, price: 1999},
          {d: 13, m: 4, y: 2018, price: 1935},
          {d: 27, m: 4, y: 2018, price: 1895},
          {d: 11, m: 5, y: 2018, price: 1999},
          {d: 18, m: 5, y: 2018, price: 1949},
          {d: 25, m: 5, y: 2018, price: 1799},
          {d: 8, m: 6, y: 2018, price: 2019},
          {d: 6, m: 7, y: 2018, price: 2675},
          {d: 20, m: 7, y: 2018, price: 2699},
          {d: 3, m: 8, y: 2018, price: 2725},
        ], 
        durability: 10, 
        route: ["Shanghai", "Beijing", "Xi'an"], 
        description: "This is the essential China tour, introducing the key sights, including the Mu Tian Yu section of the great wall, which takes you away for the main crowds and gives you fantastic opportunities to explore and take photos; the modern metropolis of Shanghai; the historic Beijing, home to some of the most stunning architectural wonders in the world including the Imperial residences and the iconic Great Wall and Xi’an, the site of one of the world’s most important archeological treasures: the army of 2,200-year-old famous Terracotta Warriors with life-size soldiers, chariots and horses buried to protect the tomb of the first Qin emperor.", 
        price: 1799
      },
      {
        hot: true, 
        img: require("./../../assets/tours/2.jpeg"), 
        name: "A Taste of India", 
        country: "India", 
        dates: [
          {d: 8, m: 3, y: 2018, price: 1199},
          {d: 12, m: 4, y: 2018, price: 1065},
          {d: 26, m: 4, y: 2018, price: 1089},
          {d: 3, m: 5, y: 2018, price: 999},
          {d: 31, m: 5, y: 2018, price: 1049},
          {d: 5, m: 6, y: 2018, price: 1145},
          {d: 2, m: 8, y: 2018, price: 1199},
          {d: 30, m: 8, y: 2018, price: 1089},
          {d: 13, m: 9, y: 2018, price: 1025},
          {d: 4, m: 10, y: 2018, price: 1229},
        ],
        durability: 7, 
        route: ["Delhi Agra", "'Pink City' Jaipur", "Fatehpur Sikri"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 999
      },
      {
        hot: false, 
        img: require("./../../assets/tours/3.jpeg"), 
        name: "A Taste of Kenya", 
        country: "Kenya", 
        dates: [
          {d: 4, m: 3, y: 2018, price: 2399},
          {d: 11, m: 3, y: 2018, price: 2439},
          {d: 18, m: 3, y: 2018, price: 2439},
          {d: 25, m: 3, y: 2018, price: 2469},
          {d: 1, m: 4, y: 2018, price: 2289},
          {d: 8, m: 4, y: 2018, price: 2325},
          {d: 15, m: 4, y: 2018, price: 2399},
          {d: 22, m: 4, y: 2018, price: 2299},
          {d: 29, m: 4, y: 2018, price: 2449},
          {d: 6, m: 5, y: 2018, price: 2499},
        ], 
        durability: 10, 
        route: ["Nairobi Masai Mara", "Lake Nakuru", "Amboseli", "Nairobi"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 2289
      },
      {
        hot: false, 
        img: require("./../../assets/tours/4.jpeg"), 
        name: "A World in One Country", 
        country: "South Africa", 
        dates: [
          {d: 1, m: 3, y: 2018, price: 3399},
          {d: 13, m: 3, y: 2018, price: 3439},
          {d: 18, m: 4, y: 2018, price: 2739},
          {d: 25, m: 4, y: 2018, price: 2769},
          {d: 1, m: 5, y: 2018, price: 2589},
          {d: 8, m: 5, y: 2018, price: 2625},
          {d: 15, m: 5, y: 2018, price: 2699},
          {d: 22, m: 6, y: 2018, price: 2599},
          {d: 29, m: 6, y: 2018, price: 2749},
          {d: 6, m: 7, y: 2018, price: 2999},
        ],
        durability: 16, 
        route: ["Johannesburg", "Pretoria", "Kruger", "Swaziland", "Zululand", "Durban", "The Garden Route", "Cape Town", "Winelands"], 
        description: "A wonderful tour where you’ll see and savour the immense richness of this beautiful region. From the wilds of Kruger National Park to the cosmopolitan sophistication of Cape Town, you’ll come to understand why South Africa is dubbed ‘A World in One Country’.",
        price: 2589
      },
      {
        hot: true, 
        img: require("./../../assets/tours/5.jpeg"), 
        name: "Bali Adventure", 
        country: "Indonesia", 
        dates: [
          {d: 3, m: 3, y: 2018, price: 1469},
          {d: 10, m: 3, y: 2018, price: 1659},
          {d: 17, m: 3, y: 2018, price: 1499},
          {d: 24, m: 3, y: 2018, price: 1699},
          {d: 31, m: 3, y: 2018, price: 1739},
          {d: 7, m: 4, y: 2018, price: 1799},
          {d: 14, m: 4, y: 2018, price: 1499},
          {d: 21, m: 4, y: 2018, price: 1499},
          {d: 28, m: 4, y: 2018, price: 1499},
          {d: 5, m: 5, y: 2018, price: 1469},
        ],  
        durability: 9, 
        route: ["Ubud", "Lovina", "Singaraja", "Menjangan Island", "Mengwi", "Tanah Lot"], 
        description: "This Bali Adventure takes you on a journey into the cultural heartland of this beautiful island. Beginning in Ubud, Bali's cultural centre, you'll travel across a landscaped filld with natural beauty, bustling markets and spectacular temples. With a chance to swim amongst some of the most pristine waters in the Indian Ocean, search for dolphins off Lovina Beach and luxuriate in the famous therapeutic springs at Banjar, this fascinating scenice odyssey also takes in the island's rich colonial history and the stunning sea temple of Tanah Lot.",
        price: 1449
      },
      {
        hot: false, 
        img: require("./../../assets/tours/6.jpeg"), 
        name: "Canadian Western Discovery", 
        country: "Canada", 
        dates: [
          {d: 6, m: 4, y: 2018, price: 2669},
          {d: 9, m: 4, y: 2018, price: 2699},
          {d: 13, m: 4, y: 2018, price: 2699},
          {d: 16, m: 4, y: 2018, price: 2699},
          {d: 20, m: 4, y: 2018, price: 2699},
          {d: 23, m: 4, y: 2018, price: 2699},
          {d: 27, m: 4, y: 2018, price: 2699},
          {d: 30, m: 4, y: 2018, price: 2699},
          {d: 3, m: 5, y: 2018, price: 2799},
          {d: 6, m: 5, y: 2018, price: 2799},
        ],  
        durability: 13, 
        route: ["Vancouver", "Kamloops", "Banff", "Jasper", "Prince George", "Victoria"], 
        description: "This route across the Rockies reveals the big picture, taking shutterhappy travellers to some of the most-snapped photo stops in western Canada — but it also reveals new view points, and gives you time to explore each big town and city your own way. Setting off in a small group adds to the authentic feeling of remoteness as you travel through the coastal mountains and high mountain passes from Vancouver to Banff. Along the way you’ll hit some of the big camera-clicking contenders, like beyond-beautiful Lake Louise; and you’ll get to taste the region’s sublime solitude with a quiet picnic among the valleys around Yoho National Park. This isn’t any ordinary road trip though — you’ll also experience Canada by rail, water, ice, and air. You’ll switch over to the railroads in Jasper, riding over the Yellowhead Pass to Prince George, with endless album-worthy scenes rolling past your window like a constantly moving flick book. You’ll get closer to nature by flying to Victoria in a small plane, soaring above the coastal fringe and over the Strait of Georgia. You’ll also board the ferry with locals, to sail to Vancouver where you’ll re-emerge in city life with a camera filled with memories.",
        price: 2699
      },

            {
        hot: true, 
        img: require("./../../assets/tours/1.jpeg"), 
        name: "A Taste of China 2", 
        country: "China", 
        dates: [
          {d: 2, m: 3, y: 2018, price: 1999},
          {d: 13, m: 4, y: 2018, price: 1935},
          {d: 27, m: 4, y: 2018, price: 1895},
          {d: 11, m: 5, y: 2018, price: 1999},
          {d: 18, m: 5, y: 2018, price: 1949},
          {d: 25, m: 5, y: 2018, price: 1799},
          {d: 8, m: 6, y: 2018, price: 2019},
          {d: 6, m: 7, y: 2018, price: 2675},
          {d: 20, m: 7, y: 2018, price: 2699},
          {d: 3, m: 8, y: 2018, price: 2725},
        ], 
        durability: 10, 
        route: ["Shanghai", "Beijing", "Xi'an"], 
        description: "This is the essential China tour, introducing the key sights, including the Mu Tian Yu section of the great wall, which takes you away for the main crowds and gives you fantastic opportunities to explore and take photos; the modern metropolis of Shanghai; the historic Beijing, home to some of the most stunning architectural wonders in the world including the Imperial residences and the iconic Great Wall and Xi’an, the site of one of the world’s most important archeological treasures: the army of 2,200-year-old famous Terracotta Warriors with life-size soldiers, chariots and horses buried to protect the tomb of the first Qin emperor.", 
        price: 1799
      },
      {
        hot: true, 
        img: require("./../../assets/tours/2.jpeg"), 
        name: "A Taste of India 2", 
        country: "India", 
        dates: [
          {d: 8, m: 3, y: 2018, price: 1199},
          {d: 12, m: 4, y: 2018, price: 1065},
          {d: 26, m: 4, y: 2018, price: 1089},
          {d: 3, m: 5, y: 2018, price: 999},
          {d: 31, m: 5, y: 2018, price: 1049},
          {d: 5, m: 6, y: 2018, price: 1145},
          {d: 2, m: 8, y: 2018, price: 1199},
          {d: 30, m: 8, y: 2018, price: 1089},
          {d: 13, m: 9, y: 2018, price: 1025},
          {d: 4, m: 10, y: 2018, price: 1229},
        ],
        durability: 7, 
        route: ["Delhi Agra", "'Pink City' Jaipur", "Fatehpur Sikri"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 999
      },
      {
        hot: false, 
        img: require("./../../assets/tours/3.jpeg"), 
        name: "A Taste of Kenya 2", 
        country: "Kenya", 
        dates: [
          {d: 4, m: 3, y: 2018, price: 2399},
          {d: 11, m: 3, y: 2018, price: 2439},
          {d: 18, m: 3, y: 2018, price: 2439},
          {d: 25, m: 3, y: 2018, price: 2469},
          {d: 1, m: 4, y: 2018, price: 2289},
          {d: 8, m: 4, y: 2018, price: 2325},
          {d: 15, m: 4, y: 2018, price: 2399},
          {d: 22, m: 4, y: 2018, price: 2299},
          {d: 29, m: 4, y: 2018, price: 2449},
          {d: 6, m: 5, y: 2018, price: 2499},
        ], 
        durability: 10, 
        route: ["Nairobi Masai Mara", "Lake Nakuru", "Amboseli", "Nairobi"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 2289
      },
      {
        hot: false, 
        img: require("./../../assets/tours/4.jpeg"), 
        name: "A World in One Country 2", 
        country: "South Africa", 
        dates: [
          {d: 1, m: 3, y: 2018, price: 3399},
          {d: 13, m: 3, y: 2018, price: 3439},
          {d: 18, m: 4, y: 2018, price: 2739},
          {d: 25, m: 4, y: 2018, price: 2769},
          {d: 1, m: 5, y: 2018, price: 2589},
          {d: 8, m: 5, y: 2018, price: 2625},
          {d: 15, m: 5, y: 2018, price: 2699},
          {d: 22, m: 6, y: 2018, price: 2599},
          {d: 29, m: 6, y: 2018, price: 2749},
          {d: 6, m: 7, y: 2018, price: 2999},
        ],
        durability: 16, 
        route: ["Johannesburg", "Pretoria", "Kruger", "Swaziland", "Zululand", "Durban", "The Garden Route", "Cape Town", "Winelands"], 
        description: "A wonderful tour where you’ll see and savour the immense richness of this beautiful region. From the wilds of Kruger National Park to the cosmopolitan sophistication of Cape Town, you’ll come to understand why South Africa is dubbed ‘A World in One Country’.",
        price: 2589
      },
      {
        hot: true, 
        img: require("./../../assets/tours/5.jpeg"), 
        name: "Bali Adventure 2", 
        country: "Indonesia", 
        dates: [
          {d: 3, m: 3, y: 2018, price: 1469},
          {d: 10, m: 3, y: 2018, price: 1659},
          {d: 17, m: 3, y: 2018, price: 1499},
          {d: 24, m: 3, y: 2018, price: 1699},
          {d: 31, m: 3, y: 2018, price: 1739},
          {d: 7, m: 4, y: 2018, price: 1799},
          {d: 14, m: 4, y: 2018, price: 1499},
          {d: 21, m: 4, y: 2018, price: 1499},
          {d: 28, m: 4, y: 2018, price: 1499},
          {d: 5, m: 5, y: 2018, price: 1469},
        ],  
        durability: 9, 
        route: ["Ubud", "Lovina", "Singaraja", "Menjangan Island", "Mengwi", "Tanah Lot"], 
        description: "This Bali Adventure takes you on a journey into the cultural heartland of this beautiful island. Beginning in Ubud, Bali's cultural centre, you'll travel across a landscaped filld with natural beauty, bustling markets and spectacular temples. With a chance to swim amongst some of the most pristine waters in the Indian Ocean, search for dolphins off Lovina Beach and luxuriate in the famous therapeutic springs at Banjar, this fascinating scenice odyssey also takes in the island's rich colonial history and the stunning sea temple of Tanah Lot.",
        price: 1449
      },
      {
        hot: false, 
        img: require("./../../assets/tours/6.jpeg"), 
        name: "Canadian Western Discovery 2", 
        country: "Canada", 
        dates: [
          {d: 6, m: 4, y: 2018, price: 2669},
          {d: 9, m: 4, y: 2018, price: 2699},
          {d: 13, m: 4, y: 2018, price: 2699},
          {d: 16, m: 4, y: 2018, price: 2699},
          {d: 20, m: 4, y: 2018, price: 2699},
          {d: 23, m: 4, y: 2018, price: 2699},
          {d: 27, m: 4, y: 2018, price: 2699},
          {d: 30, m: 4, y: 2018, price: 2699},
          {d: 3, m: 5, y: 2018, price: 2799},
          {d: 6, m: 5, y: 2018, price: 2799},
        ],  
        durability: 13, 
        route: ["Vancouver", "Kamloops", "Banff", "Jasper", "Prince George", "Victoria"], 
        description: "This route across the Rockies reveals the big picture, taking shutterhappy travellers to some of the most-snapped photo stops in western Canada — but it also reveals new view points, and gives you time to explore each big town and city your own way. Setting off in a small group adds to the authentic feeling of remoteness as you travel through the coastal mountains and high mountain passes from Vancouver to Banff. Along the way you’ll hit some of the big camera-clicking contenders, like beyond-beautiful Lake Louise; and you’ll get to taste the region’s sublime solitude with a quiet picnic among the valleys around Yoho National Park. This isn’t any ordinary road trip though — you’ll also experience Canada by rail, water, ice, and air. You’ll switch over to the railroads in Jasper, riding over the Yellowhead Pass to Prince George, with endless album-worthy scenes rolling past your window like a constantly moving flick book. You’ll get closer to nature by flying to Victoria in a small plane, soaring above the coastal fringe and over the Strait of Georgia. You’ll also board the ferry with locals, to sail to Vancouver where you’ll re-emerge in city life with a camera filled with memories.",
        price: 2699
      },


            {
        hot: true, 
        img: require("./../../assets/tours/1.jpeg"), 
        name: "A Taste of China 3", 
        country: "China", 
        dates: [
          {d: 2, m: 3, y: 2018, price: 1999},
          {d: 13, m: 4, y: 2018, price: 1935},
          {d: 27, m: 4, y: 2018, price: 1895},
          {d: 11, m: 5, y: 2018, price: 1999},
          {d: 18, m: 5, y: 2018, price: 1949},
          {d: 25, m: 5, y: 2018, price: 1799},
          {d: 8, m: 6, y: 2018, price: 2019},
          {d: 6, m: 7, y: 2018, price: 2675},
          {d: 20, m: 7, y: 2018, price: 2699},
          {d: 3, m: 8, y: 2018, price: 2725},
        ], 
        durability: 10, 
        route: ["Shanghai", "Beijing", "Xi'an"], 
        description: "This is the essential China tour, introducing the key sights, including the Mu Tian Yu section of the great wall, which takes you away for the main crowds and gives you fantastic opportunities to explore and take photos; the modern metropolis of Shanghai; the historic Beijing, home to some of the most stunning architectural wonders in the world including the Imperial residences and the iconic Great Wall and Xi’an, the site of one of the world’s most important archeological treasures: the army of 2,200-year-old famous Terracotta Warriors with life-size soldiers, chariots and horses buried to protect the tomb of the first Qin emperor.", 
        price: 1799
      },
      {
        hot: true, 
        img: require("./../../assets/tours/2.jpeg"), 
        name: "A Taste of India 3", 
        country: "India", 
        dates: [
          {d: 8, m: 3, y: 2018, price: 1199},
          {d: 12, m: 4, y: 2018, price: 1065},
          {d: 26, m: 4, y: 2018, price: 1089},
          {d: 3, m: 5, y: 2018, price: 999},
          {d: 31, m: 5, y: 2018, price: 1049},
          {d: 5, m: 6, y: 2018, price: 1145},
          {d: 2, m: 8, y: 2018, price: 1199},
          {d: 30, m: 8, y: 2018, price: 1089},
          {d: 13, m: 9, y: 2018, price: 1025},
          {d: 4, m: 10, y: 2018, price: 1229},
        ],
        durability: 7, 
        route: ["Delhi Agra", "'Pink City' Jaipur", "Fatehpur Sikri"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 999
      },
      {
        hot: false, 
        img: require("./../../assets/tours/3.jpeg"), 
        name: "A Taste of Kenya 3", 
        country: "Kenya", 
        dates: [
          {d: 4, m: 3, y: 2018, price: 2399},
          {d: 11, m: 3, y: 2018, price: 2439},
          {d: 18, m: 3, y: 2018, price: 2439},
          {d: 25, m: 3, y: 2018, price: 2469},
          {d: 1, m: 4, y: 2018, price: 2289},
          {d: 8, m: 4, y: 2018, price: 2325},
          {d: 15, m: 4, y: 2018, price: 2399},
          {d: 22, m: 4, y: 2018, price: 2299},
          {d: 29, m: 4, y: 2018, price: 2449},
          {d: 6, m: 5, y: 2018, price: 2499},
        ], 
        durability: 10, 
        route: ["Nairobi Masai Mara", "Lake Nakuru", "Amboseli", "Nairobi"], 
        description: "A chance to explore the fascinating Golden Triangle of India, a great trip for first timers or those looking for a shorter tour. Your journey begins in Delhi, where you have an opportunity to visit Old Delhi, before continuing to Agra and the iconic Taj Mahal then onwards to the ‘Pink City’ of Jaipur.", 
        price: 2289
      },
      {
        hot: false, 
        img: require("./../../assets/tours/4.jpeg"), 
        name: "A World in One Country 3", 
        country: "South Africa", 
        dates: [
          {d: 1, m: 3, y: 2018, price: 3399},
          {d: 13, m: 3, y: 2018, price: 3439},
          {d: 18, m: 4, y: 2018, price: 2739},
          {d: 25, m: 4, y: 2018, price: 2769},
          {d: 1, m: 5, y: 2018, price: 2589},
          {d: 8, m: 5, y: 2018, price: 2625},
          {d: 15, m: 5, y: 2018, price: 2699},
          {d: 22, m: 6, y: 2018, price: 2599},
          {d: 29, m: 6, y: 2018, price: 2749},
          {d: 6, m: 7, y: 2018, price: 2999},
        ],
        durability: 16, 
        route: ["Johannesburg", "Pretoria", "Kruger", "Swaziland", "Zululand", "Durban", "The Garden Route", "Cape Town", "Winelands"], 
        description: "A wonderful tour where you’ll see and savour the immense richness of this beautiful region. From the wilds of Kruger National Park to the cosmopolitan sophistication of Cape Town, you’ll come to understand why South Africa is dubbed ‘A World in One Country’.",
        price: 2589
      },
      {
        hot: true, 
        img: require("./../../assets/tours/5.jpeg"), 
        name: "Bali Adventure 3", 
        country: "Indonesia", 
        dates: [
          {d: 3, m: 3, y: 2018, price: 1469},
          {d: 10, m: 3, y: 2018, price: 1659},
          {d: 17, m: 3, y: 2018, price: 1499},
          {d: 24, m: 3, y: 2018, price: 1699},
          {d: 31, m: 3, y: 2018, price: 1739},
          {d: 7, m: 4, y: 2018, price: 1799},
          {d: 14, m: 4, y: 2018, price: 1499},
          {d: 21, m: 4, y: 2018, price: 1499},
          {d: 28, m: 4, y: 2018, price: 1499},
          {d: 5, m: 5, y: 2018, price: 1469},
        ],  
        durability: 9, 
        route: ["Ubud", "Lovina", "Singaraja", "Menjangan Island", "Mengwi", "Tanah Lot"], 
        description: "This Bali Adventure takes you on a journey into the cultural heartland of this beautiful island. Beginning in Ubud, Bali's cultural centre, you'll travel across a landscaped filld with natural beauty, bustling markets and spectacular temples. With a chance to swim amongst some of the most pristine waters in the Indian Ocean, search for dolphins off Lovina Beach and luxuriate in the famous therapeutic springs at Banjar, this fascinating scenice odyssey also takes in the island's rich colonial history and the stunning sea temple of Tanah Lot.",
        price: 1449
      },
      {
        hot: false, 
        img: require("./../../assets/tours/6.jpeg"), 
        name: "Canadian Western Discovery 3", 
        country: "Canada", 
        dates: [
          {d: 6, m: 4, y: 2018, price: 2669},
          {d: 9, m: 4, y: 2018, price: 2699},
          {d: 13, m: 4, y: 2018, price: 2699},
          {d: 16, m: 4, y: 2018, price: 2699},
          {d: 20, m: 4, y: 2018, price: 2699},
          {d: 23, m: 4, y: 2018, price: 2699},
          {d: 27, m: 4, y: 2018, price: 2699},
          {d: 30, m: 4, y: 2018, price: 2699},
          {d: 3, m: 5, y: 2018, price: 2799},
          {d: 6, m: 5, y: 2018, price: 2799},
        ],  
        durability: 13, 
        route: ["Vancouver", "Kamloops", "Banff", "Jasper", "Prince George", "Victoria"], 
        description: "This route across the Rockies reveals the big picture, taking shutterhappy travellers to some of the most-snapped photo stops in western Canada — but it also reveals new view points, and gives you time to explore each big town and city your own way. Setting off in a small group adds to the authentic feeling of remoteness as you travel through the coastal mountains and high mountain passes from Vancouver to Banff. Along the way you’ll hit some of the big camera-clicking contenders, like beyond-beautiful Lake Louise; and you’ll get to taste the region’s sublime solitude with a quiet picnic among the valleys around Yoho National Park. This isn’t any ordinary road trip though — you’ll also experience Canada by rail, water, ice, and air. You’ll switch over to the railroads in Jasper, riding over the Yellowhead Pass to Prince George, with endless album-worthy scenes rolling past your window like a constantly moving flick book. You’ll get closer to nature by flying to Victoria in a small plane, soaring above the coastal fringe and over the Strait of Georgia. You’ll also board the ferry with locals, to sail to Vancouver where you’ll re-emerge in city life with a camera filled with memories.",
        price: 2699
      },
      ],
  },

  mutations: {
    // SET_CURRENT_INDEX(state, currentIndex) {
    //   state.currentIndex = currentIndex;
    // },
    // ADD_DATA(state, data) {

    // }
  },

  actions: {
    // setCurentIndex({commit}, currentIndex){
    //   commit('SET_CURRENT_INDEX', currentIndex);
    // },
  },

  getters: {
    tours: (state) => {
      return state.tours;
    },
  },
}